/*

 WALL_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 2 x 18
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define wall_mapWidth 2
#define wall_mapHeight 18
#define wall_mapBank 0

extern unsigned char wall_map[];

/* End of WALL_MAP.H */
