/*

 SRC/WALLS.B3.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char walls[] =
{
  0xFF,0xFF,0x87,0x7C,0x06,0xFD,0x04,0xFF,
  0xFF,0xFF,0x3C,0xE3,0x30,0xEF,0x20,0xFF,
  0xFF,0xFF,0xFF,0x01,0xFD,0x03,0xC1,0x3F,
  0xC1,0x3F,0xC1,0x3F,0xC3,0x3F,0x87,0x7F
};

/* End of SRC/WALLS.B3.C */
